spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      health-check-properties: select 1  #fixme unknown property
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 0
        max-wait: 60s
  cache:
    type: redis


mybatis:
  type-aliases-package: com.mirt.sign.model

logging:
  config: classpath:logback-spring.xml