spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      connection-test-query: select 1
  redis:
    host: 192.168.12.132
    port: 63791
    jedis:
      pool:
        max-active: 20
        max-idle: 20
        min-idle: 0
        max-wait: 60s
  cache:
    type: redis

mybatis:
  type-aliases-package: com.mirt.sign.model

logging:
  config: classpath:logback-spring.xml